### ISSUE TITLE
Support for Webui Extensions

### ISSUE THREAD

**Issue by Kinsmir** [Klokinator/UnivAICharGen#1]
This would be easier for updating and maintenance in the future without having to copy over files every time.

See for context;
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions

Example with just a script
https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards

**Comment by Klokinator** [comment]
I do wish it was easier to get people updated, but this is entirely up to Umi's two coders. I just do the funny wildcard stuff haha
