### ISSUE TITLE
how

### ISSUE THREAD

**Issue by kukudoe** [Klokinator/UnivAICharGen#23]
How to manage wildcards.
I can't find Wildcards Manager

**Comment by Klokinator** [comment]
You just edit the Wildcards. With a text editor. In the folders...

**Comment by I-ShadowStar** [comment]
UmiAI does not have a built-in "manager" for wild card files. I suggest using the text editor Notepad++, which has many advanced options for managing large collections of any kind of text files.

**Comment by kukudoe** [comment]
> UmiAI does not have a built-in "manager" for wild card files. I suggest using the text editor Notepad++, which has many advanced options for managing large collections of any kind of text files.UmiAI没有内置的通配符文件管理器。我建议使用文本编辑器Notepad++，它有许多高级选项，可以管理任何类型的文本文件的大型集合。

I downlode yaml files from civitai:https://civitai.com/models/112041?modelVersionId=125505
But this yaml files can't work in UmiAi.
This yaml files can work in dynamic-prompts.

**Comment by I-ShadowStar** [comment]
> > UmiAI does not have a built-in "manager" for wild card files. I suggest using the text editor Notepad++, which has many advanced options for managing large collections of any kind of text files.UmiAI没有内置的通配符文件管理器。我建议使用文本编辑器Notepad++，它有许多高级选项，可以管理任何类型的文本文件的大型集合。
> 
> I downlode yaml files from civitai:https://civitai.com/models/112041?modelVersionId=125505 But this yaml files can't work in UmiAi. This yaml files can work in dynamic-prompts.

This is correct. CivitAI does not have a category for wildcard yaml files that work with UmiAI, only Dynamic Prompts. UmiAI is too small for CivitAI to bother with. 

This is not an issue to be fixed with UmiAI, providing compatibility with Dymanic Prompt's version of yaml files would be rude and considered taking somebody else's work without credit.
