### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Klokinator/UnivAICharGen#25]
![image](https://github.com/Klokinator/Umi-AI-Embeds/assets/60541708/f63aa01f-5a7d-49ed-a9f6-66895ac2813a)
I would like to set the default values of the "Static Wildcards".
I tried modifying the code but it's not not working, and it doesn't save the setting when you restart the editor.

**Comment by Clonephaze** [comment]
You could just use the stock "defaults" settings tab to set it yourself, as you can see in the screenshot.
![image](https://github.com/Klokinator/Umi-AI-Embeds/assets/6809805/8458a2f1-1d47-4ba3-96e8-b0b05675d70c)
Just open webui, change the settings, go to your defaults tab in your settings, click view changes to make sure it took, click apply. Now each time you launch webui it will be set for you.

**Comment by MNeMoNiCuZ** [comment]
Ohh, didn't know that was a thing! That's great, thank you very much.
That would certainly be a good solution to this.

If more people don't know about it, maybe it could be a good thing to add in the instructions/guide/help-tab possibly?

Anyway, thanks!

**Comment by I-ShadowStar** [comment]
The 'Defaults' settings tab of Automatic 1111 was recently added, with ver 1.5.x iirc. It works for all things displayed on the image generation tabs. The author of A1111 has included instructions for using this new feature on their Git pages.

You can manually set default values for practically any extension by editing the ui-config.json file in the root of the A1111 folders. This is essentially what the new 'defaults' feature of A1111 is doing behind the scenes anyway.

**Comment by MNeMoNiCuZ** [comment]
Yeah this is fantastic, I've fixed so many small things that's been bothering me all this time thanks to this!

**Comment by Clonephaze** [comment]
> Yeah this is fantastic, I've fixed so many small things that's been bothering me all this time thanks to this!

If you like that, you should check out the extension [Config-Presets](https://github.com/Zyin055/Config-Presets). Lets you have defaults for different situations. I love it personally. Also, you could probably close this issue as it's not really something the author will need to put into the extension itself.
